// NOTE: THIS FILE WAS AUTOMATICALLY GENERATED BY mai-protocol-v2

export const testRpc = 'http://server10.jy.mcarlo.com:8745' // mai2js_admin
export const testContractReader = "0x8CA71FFa0c9406C0c249575e851cB84EB6F00E69"
export const testAdmin = '0x6766F3CFD606E1E428747D3364baE65B6f914D56'
export const testDev = '0x6766F3CFD606E1E428747D3364baE65B6f914D56'
export const testU2 = '0x3eB06F432aE8f518A957852AA44776c234b4a84a'
export const testU7 = '0x6109d8Fdb3104bc329f7FA1d29c6b4A9A4D3F6AC'
export const testUser = '0x6109d8fdb3104bc329f7fa1d29c6b4a9a4d3f6ac' // address (7) in our ganache test env
export const testUserPK = '0x1c6a05d6d52954b74407a62f000450d0a748d26a7cc3477cd7f8d7c41d4992ce' // address (2) in our ganache test env
export const dataTestAddress = {
    perp: '0x45e4C467b3f7D214Dbfb06467F471270Afa2Af92',
    perpProxy: '0xd6b8CDe2A90C9D4B35690b09770E574614a75a97',
    amm: '0x0776B92C3dF01fc1d49dcc24F61Ea4D867B9Ff58',
    testToken: '0x23DCbBec4d7575285e0111310A4467ACa08AAa4E',
}
export const transactTestAddress = {
    perp: '0x754864057FE0D237B217fBCd5d4364415ecd2Fb8',
    perpProxy: '0xe081a8743951042f3f07F78c0516c23063DB407c',
    amm: '0x5C1d6702277eadbe186Dc3B72f3da5973Fe41e63',
    testToken: '0x3530083018b3D83844856753581C0656EA521840',
}
export const transactEthTestAddress = {
    perp: '0x38a0Bc5Ef82eb7a4DC879499C6643b230feC041c',
    perpProxy: '0xFe13b5cAdBada2300945Bde26967bfb6142f2096',
    amm: '0xEa6EF625Bbf734901884B44F075bdAB63c2f6c35',
    testToken: '0x0000000000000000000000000000000000000000',
}