// NOTE: THIS FILE WAS AUTOMATICALLY GENERATED BY mai-protocol-v2

export const testRpc = 'http://127.0.0.1:8545' // mai2js_admin
export const testContractReader = "0x89216c616B1D69Ae3E27b7fde3236A96943495eb"
export const testAdmin = '0x6766F3CFD606E1E428747D3364baE65B6f914D56'
export const testDev = '0x6766F3CFD606E1E428747D3364baE65B6f914D56'
export const testU2 = '0x3eB06F432aE8f518A957852AA44776c234b4a84a'
export const testU7 = '0x6109d8Fdb3104bc329f7FA1d29c6b4A9A4D3F6AC'
export const testUser = '0x6109d8fdb3104bc329f7fa1d29c6b4a9a4d3f6ac' // address (7) in our ganache test env
export const testUserPK = '0x1c6a05d6d52954b74407a62f000450d0a748d26a7cc3477cd7f8d7c41d4992ce' // address (2) in our ganache test env
export const dataTestAddress = {
    perp: '0x52ec99582A26DD95268Df31Ed8d8e05334668881',
    perpProxy: '0x2bF4184C5468D9E77de85f77947aBa074C7014Cf',
    amm: '0x7285b7dA73eED1D7F1AA03b35C6a46B3c5031eB3',
    testToken: '0xD62c320A96EaEb45f774Eb441D929396A904fc9c',
}
export const transactTestAddress = {
    perp: '0x3A17a11B4f59a99650651F0A1dF7390d912CF548',
    perpProxy: '0xe04Cd37DE66AA09aB5da84a08d7A342661884dce',
    amm: '0xfC0f0E61611BE72e78D31746B8cF27Bb51e69706',
    testToken: '0x822c22b75CEB9aC3fE2091424f10E3EcaACaFDBe',
}
export const transactEthTestAddress = {
    perp: '0xf5232260f48B37d3544885FaE2C1F81C0ea4b6Fd',
    perpProxy: '0x1d3503Cd298255bE96407D80885ceA0E5f10eB4b',
    amm: '0x693F9fEBdF745b7Ef8d12DaA1cDB7010AC2B73bf',
    testToken: '0x0000000000000000000000000000000000000000',
}