// NOTE: THIS FILE WAS AUTOMATICALLY GENERATED BY mai-protocol-v2

export const testRpc = 'http://server10.jy.mcarlo.com:8745'
export const testUser = '0x6109d8fdb3104bc329f7fa1d29c6b4a9a4d3f6ac' // address (7) in our ganache test env
export const testUserPK = '0x1c6a05d6d52954b74407a62f000450d0a748d26a7cc3477cd7f8d7c41d4992ce' // address (2) in our ganache test env
export const dataTestAddress = {
    perp: '0x434ae4b4dD0069D59a4774d4FE8eE293F84c0baE',
    perpProxy: '0x9Cd17af25a2C4a0089805D23e1290B21C03868b7',
    amm: '0xeC3Be94B89219E73fAB12D3C0E3a1B9E4E62d482'
}
export const transactTestAddress = {
    perp: '0xdd22dF8d692f9e4727A2a5a8Ed1C2d1354793389',
    perpProxy: '0xF070E6C301C9Cd082d136Ef8d8C8ff4915fB7ADe',
    amm: '0xb5220f24124A6D43CB0EF360236bd10Ba4170e94'
}
export const transactEthTestAddress = {
    perp: '0x89C87CeA71967821f4950cDd8034c41aD1c4cDC1',
    perpProxy: '0x36432E2fC2d174Dd055903FA6AfEaeb69B2b73f5',
    amm: '0x38c2f2E9c2Fc188199eD09c601f753Cf4e8e5bBB'
}
